name: 1loc_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
    - master

pr:
    - master

schedules:
    - cron: "0 0 * * *"
      displayName: Daily midnight build
      branches:
          include:
              - master

stages:
    - stage: __default
      jobs:
          - job: Job1
            pool:
                vmImage: windows-latest
            steps:
                - task: cesve.one-loc-build.one-loc-build.OneLocBuild@1
                  env:
                      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
                  displayName: "Localization Build: src/language-services/localization/LocProject.json"
                  inputs:
                      locProj: src/language-services/localization/LocProject.json
                      packageSourceAuth: patAuth
                      patVariable: "$(OneLocBuildPAT)"

                - task: PublishBuildArtifacts@1
                  displayName: "Publish Artifact: drop"
